### ISSUE TITLE
サンプルコードのYOUR_APPLICATION_IDの箇所について 

### ISSUE THREAD

**Issue by YU-TAYU** [rakuten-ws/rws-ruby-sdk#14]
# 概要
サンプルのYOUR_APPLICATION_IDの部分で自分のIDが必要だと言うことがわからなかったので、READMEに書いてあると嬉しいです。

# 詳細
README.mdを見ながらrubyを実際に動かそうとしていました。まず最初のサンプルを実行させました。参照したのは以下の部分です。
https://github.com/rakuten-ws/rws-ruby-sdk#設定

```ruby
RakutenWebService.configuration do |c|
    c.application_id = YOUR_APPLICATION_ID
    c.affiliate_id = YOUR_AFFILIATE_ID
  end
```
しかし、最初のサンプルでエラーが出て、そのエラーは以下のものでした。
```
test_rakuten.rb:8:in `block in <main>': uninitialized constant YOUR_APPLICATION_ID (NameError)
	from /Users/yuki/gem/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/configuration.rb:20:in `call'
	from /Users/yuki/gem/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/configuration.rb:20:in `configuration'
	from test_rakuten.rb:7:in `<main>'
```
エラーを見たところによるとYOUR_APPLICATION_IDが見つからないようでした。調べてみるとアプリケーションIDを取得しないといけないことがわかりました。そこで楽天のweb serviceで登録をしました。
改善点としてIDを取得しないといけない旨を記載しておくこと、また、web serviceの登録リンクを記載しておいた方がわかりやすいと考えました。　(リンクは以下のものです。)
https://webservice.rakuten.co.jp/app/create

そして、IDを取得したあとYOUR_APPLICATION_IDを自分のIDに入れ替えたのですが、シングルクォートで囲むことを忘れていたので、その旨も記載しておくと、分かりやすいと考えます。
実際にすぐに使えるようなexampleのIDも記載してあるサンプルコードがあるとわかりやすいと感じました。

**Comment by satoryu** [comment]
- [ ] README.md に、アプリケーションIDの取得方法について記載
- [ ] README.md 中の`YOUR_APPLICATION_ID` の扱い方を記載

> 実際にすぐに使えるようなexampleのIDも記載してあるサンプルコードがあるとわかりやすいと感じました。

これは実現可能なのかどうか、ウェブサービス担当に確認します。
このIDを元に、利用状況の確認、不正利用の場合の利用制限などを行っているので、1つ自由なIDを公開してしまうと、それらの制御ができなくなると思われます。

**Comment by satoryu** [comment]
@YU-TAYU PR #20 を送りました。コメントいただけると助かります。
