### ISSUE TITLE
RakutenWebService::Ichiba::Genre[100316].rankingでundefined methodが出る

### ISSUE THREAD

**Issue by sky-oozora-bbbs** [rakuten-ws/rws-ruby-sdk#15]
# 問題
https://github.com/rakuten-ws/rws-ruby-sdk#市場商品ランキング の例に

> RakutenWebService::Ichiba::Genre[100316].ranking # "水・ソフトドリンク" ジャンルのTOP 30

という記述があり、それを取得しようとしたところ、以下のエラーが出力された。
> ichiba_ranking.rb:11:in `<main>': undefined method `ranking' for nil:NilClass (NoMethodError)

## 前提条件
https://github.com/rakuten-ws/rws-ruby-sdk#user-content-%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E6%96%B9%E6%B3%95 の通りに、
> $ gem install rakuten_web_service

でrws-ruby-sdkをインストールした。

## 実行コマンド
> $ ruby ichiba_ranking.rb [my_application_id]

## プログラムソース
```Ruby
# encoding: utf-8

 require 'rakuten_web_service'

 application_id = ARGV.shift

 RakutenWebService.configuration do |c|
   c.application_id = application_id
 end
 
 rank = RakutenWebService::Ichiba::Genre[100316].ranking
 
 rank.first(10).each do |item|
   puts "#{item['itemName']}, #{item['itemPrice']} yen"
 end
```

## 開発環境
Rubyのバージョン: 2.2.2
OS: ubuntu 14.04 LTS

## 改善策
> RakutenWebService::Ichiba::Genre[100316].ranking

を

> RakutenWebService::Ichiba::Genre.new(100316).ranking

に書き換えたところ結果が表示された。

**Comment by satoryu** [comment]
@sky-oozora-bbbs  #21 で修正しました。

`RakutenWebService::Ichiba::Genre.new(100316)` を実行した後に、`RakutenWebService::Ichiba::Genre[100316]` を実行すると問題はなかったのですが、初回に実行すると `nil` が出るバグでした。
これを、初回実行時に `nil` を返さないようにしました。

**Comment by sky-oozora-bbbs** [comment]
@satoryu 
なるほど、ご丁寧にありがとうございます。
これからもrws-ruby-sdkが発展していくことを願ってます！
