### ISSUE TITLE
付属のサンプルコード実行時にエラーが出る問題について

### ISSUE THREAD

**Issue by neisunwere** [rakuten-ws/rws-ruby-sdk#16]
### 問題内容

rws-ruby-sdkをForkし、ローカルリポジトリにcloneした。その後、rws-ruby-sdk/examples/ichiba_item_search.rbをターミナル上で実行しようとすると、
> .rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/client.rb:18:in `initialize': uninitialized constant RakutenWebService::Client::URI (NameError)

とエラーが出る。
application_idには楽天ウェブサービスで新規アプリ登録をした際に発行された値を与えている。

***実行環境***
Ubuntu 14.04, ruby 2.2.0 

−−−−−−−−
### 解決方法

> rws-ruby-sdk/examples/ichiba_item_search.rb
> rws-ruby-sdk/lib/rakuten_web_service/client.rb

の行頭に
> require 'uri'

を追加した。

***ichiba_item_search.rb***
修正前
> \# encoding: utf-8
> require 'rakuten_web_service'

修正後
> \# encoding: utf-8
> require 'rakuten_web_service'
> require 'uri'

***client.rb***
修正前
> require 'faraday'
> require 'faraday_middleware'
> require 'rakuten_web_service/response'

修正後
> require 'faraday'
> require 'faraday_middleware'
> require 'rakuten_web_service/response'
> require 'uri'

**Comment by satoryu** [comment]
修正前、修正後の部分については、実際にソースコードを変更して、pull requestで送ると、お互いに間違いを減らせます。

もし、pull requestの作成方法がわからないようであれば、メンターまで :+1:

**Comment by satoryu** [comment]
#18 と同じなので、そちらにまとめるため、Close します。
報告ありがとうございました :raised_hands:

**Comment by satoryu** [comment]
@neisunwere プルリクエストはもちろんお待ちしております！
