### ISSUE TITLE
rws-ruby-sdk/spec/fixtures/books/foreign_book_search_with_keyword_Ruby.jsonのメッセージにtypo

### ISSUE THREAD

**Issue by sky-oozora-bbbs** [rakuten-ws/rws-ruby-sdk#19]
> Support RWS::Books::ForeginBook API

これはおそらくtypo :smiley: 

> Support RWS::Books::ForeignBook API

ではないでしょうか。

**Comment by satoryu** [comment]
@sky-oozora-bbbs 

どのファイルの何行目あたりでしょうか？

**Comment by satoryu** [comment]
```sh
$ cd rws-ruby-sdk
$ grep -rn Foreign ./spec
$
```

とくに見当たらないのですが、このTypoはどこにあるのでしょうか？

**Comment by sky-oozora-bbbs** [comment]
![screenshot from 2015-06-27 16 54 33](https://cloud.githubusercontent.com/assets/12743957/8391072/87d9d744-1ced-11e5-9238-cf3216541442.png)

SSですみません。
この写真の真ん中辺りです。

**Comment by satoryu** [comment]
@sky-oozora-bbbs これは コミットのログメッセージですね。 2c4683fffad2132e3752a069204f818922744d2d

これは基本的に、ユーザーが見える表には出ないもので、機能的にも問題無いので、Close させてください :bow:
