### ISSUE TITLE
Support GOLA API

### ISSUE THREAD

**Issue by satoryu** [rakuten-ws/rws-ruby-sdk#28]
I found @kamatama41's [branch for supporting GOLA API](https://github.com/kamatama41/rws-ruby-sdk/tree/support-gora) in his repository! and it looks good to me. 
@kamatama41 Do you think you can open a pull request?

**Comment by kamatama41** [comment]
@satoryu 
Thanks for finding my branch. 
The branch was for my personal project but it's not proceeded..
So it's WIP yet and I'm not sure it has enough quality for production use.
If that's OK with you, I'll create a PR 😃

**Comment by satoryu** [comment]
Yes, please open new PR [here](https://github.com/rakuten-ws/rws-ruby-sdk/compare/master...kamatama41:support-gora). 
Let us check the branch together :)

**Comment by satoryu** [comment]
@kamatama41  Thank you for your contribution 🍣
