### ISSUE TITLE
How to get product list of any publisher?

### ISSUE THREAD

**Issue by tarasinsky** [rakuten-ws/rws-ruby-sdk#69]
Hello!
Using Rakuten LinkShare portal.  There is the ["Product LinkFinder"](https://www.dropbox.com/s/gjn7uixzrimq8kt/Rakuten.png?dl=0) function to search for products and get product list with product title, description, photo, price.
Is it possible to get product list with rws-ruby-sdk?

Thanks in advance.

**Comment by satoryu** [comment]
Hi, 

Now this gem is supporting [Rakuten Web Service's APIs](http://webservice.rakuten.co.jp/), not LinkShare's ones. 
Rakuten Web Service has [Product API](http://webservice.rakuten.co.jp/api/productsearch/) (in Japanese only) but I'm not sure it's possible to get the list you want.

**Comment by tarasinsky** [comment]
Hi,

Thanks for help!

Regards,
Aleksandr

2017-02-08 17:12 GMT+03:00 Tatsuya Sato <notifications@github.com>:
